### ISSUE TITLE
Some animations joining absolute divs

### ISSUE THREAD

**Issue by cptx032** [dixso/custombox#168]
When I have a div with absolute position, like
```css
.footer {
    position: absolute;
    bottom: 0px;
}
```
```html
<a href="#" onclick="showmodal()">Click to, temporally, bring footer to center</a>

<div class="footer">Footer</div>
```
and the 'effect' param is blur, letmein, slip, contentscale or push, the footer is centralized together with the link while the modal is showing
Example here:
http://codepen.io/anon/pen/gPopLj
